#!/usr/bin/env python3
# Extracted verbatim from notebooks/trainingpipeline-v1.ipynb (cells [4, 5, 6, 7, 8, 9, 11]).
# Logic is unchanged from the run that produced the reported results.
# Paths below are the original Kaggle absolute paths; see README "Reproducing".

import os
import re
import glob
import json
import csv
import math
import numpy as np
import cv2
import torch
import torch.nn as nn
import torch.nn.functional as F

"""
Train + compare three BEV occupancy fusion strategies on the KITTI pseudo-labels
generated by kitti_bev_pseudolabels.py:
  1. Hand-tuned fixed weights (your paper's original: 0.5*density + 0.2*edge + 0.3*yolo)
  2. FusionMLP (per-cell, learned, 5 input channels)
  3. U-Net + PatchGAN (spatial, learned, same 5 input channels)
 
Reports held-out IoU/F1 for all three on the same split, so the comparison is
apples-to-apples. Run this AFTER kitti_bev_pseudolabels.py has populated
/kaggle/working/bev_pseudolabels/ with .pt pairs.
 
pip install: torch torchvision numpy
"""
 
import os
import re
import glob
import numpy as np
import cv2
import torch
from ultralytics import YOLO

KITTI_ROOT = "/kaggle/input/datasets/artemmmtry/kitti-depth-prediction-evaluation"
VAL_SEL_DIR = os.path.join(KITTI_ROOT, "data_depth_selection", "depth_selection", "val_selection_cropped")
IMAGE_DIR = os.path.join(VAL_SEL_DIR, "image")
DEPTH_DIR = os.path.join(VAL_SEL_DIR, "groundtruth_depth")
INTRINSICS_DIR = os.path.join(VAL_SEL_DIR, "intrinsics")

OUT_DIR = "/kaggle/working/bev_pseudolabels"
os.makedirs(OUT_DIR, exist_ok=True)

GRID_RANGE_FWD = 40.0
GRID_RANGE_LAT = 20.0
CELL_SIZE = 0.2
GRID_H = int(GRID_RANGE_FWD / CELL_SIZE)
GRID_W = int(2 * GRID_RANGE_LAT / CELL_SIZE)

MIN_POINTS_OCCUPIED = 3
YOLO_CONF_THRESH = 0.35
YOLO_CLASSES = [2, 3, 5, 7]
EDGE_WEIGHTS = (0.4, 0.4, 0.2)

def load_frame_intrinsics(txt_path):
    with open(txt_path, "r") as f:
        vals = np.array([float(x) for x in f.read().split()])
    if vals.size == 9:
        K = vals.reshape(3, 3)
    elif vals.size == 12:
        K = vals.reshape(3, 4)[:, :3]
    else:
        raise ValueError(f"Unexpected intrinsics format ({vals.size} values) in {txt_path}")
    fx, fy = K[0, 0], K[1, 1]
    cx, cy = K[0, 2], K[1, 2]
    return fx, fy, cx, cy

DEFAULT_FX, DEFAULT_FY = 721.5377, 721.5377
DEFAULT_CX, DEFAULT_CY = 609.5593, 172.8540

def load_kitti_depth_png(path):
    depth_raw = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    if depth_raw is None:
        raise FileNotFoundError(path)
    depth_m = depth_raw.astype(np.float32) / 256.0
    depth_m[depth_raw == 0] = 0.0
    return depth_m

def backproject_to_bev(depth_m, fx, fy, cx, cy):
    H, W = depth_m.shape
    us, vs = np.meshgrid(np.arange(W), np.arange(H))
    valid = depth_m > 0
    Z = depth_m[valid]
    X = (us[valid] - cx) * Z / fx
    row = (Z / CELL_SIZE).astype(np.int32)
    col = ((X + GRID_RANGE_LAT) / CELL_SIZE).astype(np.int32)
    in_range = (row >= 0) & (row < GRID_H) & (col >= 0) & (col < GRID_W)
    row, col, Z = row[in_range], col[in_range], Z[in_range]
    count_grid = np.zeros((GRID_H, GRID_W), dtype=np.int32)
    depth_sum_grid = np.zeros((GRID_H, GRID_W), dtype=np.float64)
    depth_sq_sum_grid = np.zeros((GRID_H, GRID_W), dtype=np.float64)
    np.add.at(count_grid, (row, col), 1)
    np.add.at(depth_sum_grid, (row, col), Z)
    np.add.at(depth_sq_sum_grid, (row, col), Z ** 2)
    return count_grid, depth_sum_grid, depth_sq_sum_grid

def make_pseudo_occupancy_label(count_grid, k=MIN_POINTS_OCCUPIED):
    return (count_grid >= k).astype(np.float32)

def make_depth_mean_var(count_grid, depth_sum_grid, depth_sq_sum_grid):
    with np.errstate(divide="ignore", invalid="ignore"):
        mean = np.where(count_grid > 0, depth_sum_grid / np.maximum(count_grid, 1), 0.0)
        var = np.where(count_grid > 0, depth_sq_sum_grid / np.maximum(count_grid, 1) - mean ** 2, 0.0)
    var = np.clip(var, 0.0, None)
    return mean.astype(np.float32), var.astype(np.float32)

def make_density_map(count_grid):
    if count_grid.max() == 0:
        return np.zeros_like(count_grid, dtype=np.float32)
    return (count_grid / count_grid.max()).astype(np.float32)

def make_edge_confidence_map(rgb_img, weights=EDGE_WEIGHTS):
    gray = cv2.cvtColor(rgb_img, cv2.COLOR_BGR2GRAY)
    canny = cv2.Canny(gray, 50, 150).astype(np.float32) / 255.0
    sobel_x = cv2.Sobel(gray, cv2.CV_32F, 1, 0, ksize=3)
    sobel_y = cv2.Sobel(gray, cv2.CV_32F, 0, 1, ksize=3)
    sobel_mag = np.sqrt(sobel_x ** 2 + sobel_y ** 2)
    sobel_norm = sobel_mag / (sobel_mag.max() + 1e-6)
    emboss_kernel = np.array([[-2, -1, 0], [-1, 1, 1], [0, 1, 2]], dtype=np.float32)
    emboss = cv2.filter2D(gray.astype(np.float32), -1, emboss_kernel)
    emboss_norm = np.abs(emboss) / (np.abs(emboss).max() + 1e-6)
    w_canny, w_sobel, w_emboss = weights
    return w_canny * canny + w_sobel * sobel_norm + w_emboss * emboss_norm

def project_image_map_to_bev(img_space_map, depth_m, fx, fy, cx, cy):
    H, W = depth_m.shape
    us, vs = np.meshgrid(np.arange(W), np.arange(H))
    valid = depth_m > 0
    Z = depth_m[valid]
    X = (us[valid] - cx) * Z / fx
    vals = img_space_map[valid]
    row = (Z / CELL_SIZE).astype(np.int32)
    col = ((X + GRID_RANGE_LAT) / CELL_SIZE).astype(np.int32)
    in_range = (row >= 0) & (row < GRID_H) & (col >= 0) & (col < GRID_W)
    row, col, vals = row[in_range], col[in_range], vals[in_range]
    sum_grid = np.zeros((GRID_H, GRID_W), dtype=np.float64)
    count_grid = np.zeros((GRID_H, GRID_W), dtype=np.int32)
    np.add.at(sum_grid, (row, col), vals)
    np.add.at(count_grid, (row, col), 1)
    with np.errstate(divide="ignore", invalid="ignore"):
        mean_grid = np.where(count_grid > 0, sum_grid / np.maximum(count_grid, 1), 0.0)
    return mean_grid.astype(np.float32)

_yolo_model = None

def get_yolo_model():
    global _yolo_model
    if _yolo_model is None:
        _yolo_model = YOLO("yolov8n.pt")
    return _yolo_model

def make_yolo_conf_map(rgb_img, depth_m, fx, fy, cx, cy):
    model = get_yolo_model()
    results = model(rgb_img, verbose=False)[0]
    conf_grid = np.zeros((GRID_H, GRID_W), dtype=np.float32)
    for box in results.boxes:
        cls_id = int(box.cls.item())
        conf = float(box.conf.item())
        if cls_id not in YOLO_CLASSES or conf < YOLO_CONF_THRESH:
            continue
        x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
        u_bc, v_bc = int((x1 + x2) / 2), int(y2)
        v_bc = np.clip(v_bc, 0, depth_m.shape[0] - 1)
        u_bc = np.clip(u_bc, 0, depth_m.shape[1] - 1)
        Z = depth_m[v_bc, u_bc]
        if Z <= 0:
            continue
        X = (u_bc - cx) * Z / fx
        row, col = int(Z / CELL_SIZE), int((X + GRID_RANGE_LAT) / CELL_SIZE)
        if 0 <= row < GRID_H and 0 <= col < GRID_W:
            r0, r1 = max(0, row - 1), min(GRID_H, row + 2)
            c0, c1 = max(0, col - 1), min(GRID_W, col + 2)
            conf_grid[r0:r1, c0:c1] = np.maximum(conf_grid[r0:r1, c0:c1], conf)
    return conf_grid

def process_one_image(rgb_path, depth_path, fx, fy, cx, cy):
    rgb = cv2.imread(rgb_path)
    depth_m = load_kitti_depth_png(depth_path)
    if rgb.shape[:2] != depth_m.shape[:2]:
        rgb = cv2.resize(rgb, (depth_m.shape[1], depth_m.shape[0]))
    count_grid, depth_sum_grid, depth_sq_sum_grid = backproject_to_bev(depth_m, fx, fy, cx, cy)
    label = make_pseudo_occupancy_label(count_grid)
    density = make_density_map(count_grid)
    depth_mean, depth_var = make_depth_mean_var(count_grid, depth_sum_grid, depth_sq_sum_grid)
    edge_conf_img_space = make_edge_confidence_map(rgb)
    edge_conf_bev = project_image_map_to_bev(edge_conf_img_space, depth_m, fx, fy, cx, cy)
    yolo_conf_bev = make_yolo_conf_map(rgb, depth_m, fx, fy, cx, cy)
    input_stack = np.stack([density, edge_conf_bev, yolo_conf_bev, depth_mean, depth_var], axis=0)
    return input_stack.astype(np.float32), label.astype(np.float32)

def image_name_to_depth_name(image_filename):
    return image_filename.replace("_image_", "_groundtruth_depth_", 1)

def main():
    image_paths = sorted(glob.glob(os.path.join(IMAGE_DIR, "*.png")))
    print(f"Found {len(image_paths)} images in {IMAGE_DIR}")
    if len(image_paths) == 0:
        print("0 images found -- check KITTI_ROOT / VAL_SEL_DIR.")
        return
    saved = 0
    for rgb_path in image_paths:
        image_filename = os.path.basename(rgb_path)
        depth_filename = image_name_to_depth_name(image_filename)
        depth_path = os.path.join(DEPTH_DIR, depth_filename)
        intrinsics_path = os.path.join(INTRINSICS_DIR, image_filename.replace(".png", ".txt"))
        if not os.path.exists(depth_path):
            print(f"skip {image_filename}: no matching GT depth at {depth_filename}")
            continue
        if os.path.exists(intrinsics_path):
            try:
                fx, fy, cx, cy = load_frame_intrinsics(intrinsics_path)
            except Exception as e:
                fx, fy, cx, cy = DEFAULT_FX, DEFAULT_FY, DEFAULT_CX, DEFAULT_CY
        else:
            fx, fy, cx, cy = DEFAULT_FX, DEFAULT_FY, DEFAULT_CX, DEFAULT_CY
        try:
            input_stack, label = process_one_image(rgb_path, depth_path, fx, fy, cx, cy)
        except Exception as e:
            print(f"skip {image_filename}: {e}")
            continue
        out_name = image_filename.replace(".png", ".pt")
        torch.save({"input": torch.from_numpy(input_stack), "label": torch.from_numpy(label)},
                   os.path.join(OUT_DIR, out_name))
        saved += 1
        if saved % 50 == 0:
            print(f"saved {saved} pairs...")
    print(f"Done. Saved {saved} (input, label) pairs to {OUT_DIR}")

main()
